name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Some tests may need the package itself
          pip install -e .

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=100

      - name: Run tests with pytest
        env:
          # If your tests execute training, ensure they can find model/data
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q
