name: Model Monitoring

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual trigger from GitHub UI

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run monitoring script
        run: python src/monitor.py

      - name: Archive monitoring reports
        uses: actions/upload-artifact@v2
        with:
          name: monitoring-reports
          path: reports/
